// Code generated by goctl. DO NOT EDIT!
// Source: add.proto

//go:generate mockgen -destination ./adder_mock.go -package adder -source $GOFILE

package adder

import (
	"context"

	"bookstore/rpc/add/add"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	AddReq  = add.AddReq
	AddResp = add.AddResp

	Adder interface {
		Add(ctx context.Context, in *AddReq) (*AddResp, error)
	}

	defaultAdder struct {
		cli zrpc.Client
	}
)

func NewAdder(cli zrpc.Client) Adder {
	return &defaultAdder{
		cli: cli,
	}
}

func (m *defaultAdder) Add(ctx context.Context, in *AddReq) (*AddResp, error) {
	// TODO 构建gRpc接口调用客户端
	client := add.NewAdderClient(m.cli.Conn())
	// TODO 调用gRpc接口
	return client.Add(ctx, in)
}
